# fly.toml app configuration file generated for km-members-only on 2023-09-08T15:27:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "km-members-only"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
